name: scored
description: Scored! allows you to keep track of all your scores, or whatever else you may want to keep track off!
publish_to: 'none'
version: 2.0.0+13

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flex_color_picker: ^2.1.2
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_slidable: ^0.6.0
    flutter_spinbox: ^0.5.2
    hive: ^2.0.4
    hive_flutter: ^1.1.0
    intl: ^0.17.0
    path_provider: ^2.0.2
    provider: ^5.0.0
    shared_preferences: ^2.0.6
    url_launcher: ^6.0.9

dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^1.1.0
    build_runner: ^2.0.6

flutter:
    uses-material-design: true
flutter_intl:
    enabled: true
