name: scored
description: Scored! allows you to keep track of all your scores, or whatever else you may want to keep track off !
publish_to: 'none'
version: 1.0.0+9

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_spinbox: ^0.5.2
    flutter_svg: ^0.22.0
    provider: ^5.0.0
    shared_preferences: ^2.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/arrow_down.svg
